### ISSUE TITLE
I wish to add a  responsive website of a hotel 

### ISSUE THREAD

**Issue by Paras022** [ZeroOctave/Web-Development-DBMS-Projects-Basket#3]
would like to contribute a design of a responsive Hotel website that has appealing effects when you hover over the images and a well structured website with functional navbars . It will have login , registration and reservation forms .

**Comment by Astrodevil** [comment]
Will it include databases or backend? or just html,css,js

**Comment by Paras022** [comment]
Yes , it includes backend . backend work is done using PHP to validate the forms and all . The data of  user is stored in phpmyadmin .

**Comment by Astrodevil** [comment]
Also attach a proper markdown file to setup and run the whole projects.
